#!/usr/bin/python3

# Install and run the server
import config as c
import os

config = c.load_config()

world_link = config["world_link"]
server_link = config["server-link"]
extract = config["extract"]

# Symlink the other shit
# TODO: add ability to change the install location
os.symlink("backup.py","/usr/local/bin/backup")
os.symlink("destroy.py", "/usr/local/bin/destroy")

# Replace with the config
server_root = config["root_directory"]
server_name = "server.%s"%("zip" if extract else "jar")
print(server_name)

try:
    os.mkdir(server_root)
except FileExistsError:
    pass

os.chdir(server_root)

os.system(f'wget {server_link} -O {server_name}')
if extract: 
    os.system(f'unzip {server_name}')


if world_link:
    os.system(f'wget {world_link} -O world.zip')
    os.system(f'unzip world.zip')
    os.remove("world.zip")

os.system(f"screen -S server -dm \"{config['start-cmd']}\"")
